// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNE5k6E-ROrpa7TqeHKvjGX7UsbsvA3kY',
    appId: '1:607855529793:web:1fa0ba445eddde920c1bc0',
    messagingSenderId: '607855529793',
    projectId: 'examgo-31b5b',
    authDomain: 'examgo-31b5b.firebaseapp.com',
    storageBucket: 'examgo-31b5b.firebasestorage.app',
    measurementId: 'G-P63Q0S77V9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-Qt24TtXQ5siKKkATzBKUG3PPW58JfaM',
    appId: '1:607855529793:android:37314c7f5520763f0c1bc0',
    messagingSenderId: '607855529793',
    projectId: 'examgo-31b5b',
    storageBucket: 'examgo-31b5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBmNDKNuI8--s7l4QZlmYbPg4-jMfX8cM',
    appId: '1:607855529793:ios:3a3b85a80bbd256a0c1bc0',
    messagingSenderId: '607855529793',
    projectId: 'examgo-31b5b',
    storageBucket: 'examgo-31b5b.firebasestorage.app',
    iosBundleId: 'com.kemenag.examgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBmNDKNuI8--s7l4QZlmYbPg4-jMfX8cM',
    appId: '1:607855529793:ios:1c6c1fdbc7a8936c0c1bc0',
    messagingSenderId: '607855529793',
    projectId: 'examgo-31b5b',
    storageBucket: 'examgo-31b5b.firebasestorage.app',
    iosBundleId: 'com.example.examgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNE5k6E-ROrpa7TqeHKvjGX7UsbsvA3kY',
    appId: '1:607855529793:web:c5576f9fc458b2730c1bc0',
    messagingSenderId: '607855529793',
    projectId: 'examgo-31b5b',
    authDomain: 'examgo-31b5b.firebaseapp.com',
    storageBucket: 'examgo-31b5b.firebasestorage.app',
    measurementId: 'G-KT62XF6LXS',
  );
}
